---
abstract: 'Convert Markdown to POD'
author:
  - 'Keedi Kim - 김도형 <keedi@cpan.org>'
build_requires:
  Exporter: 5.57
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Markdown-Pod
requires:
  Getopt::Long: 0
  List::Util: 0
  Markdent: 0.23
  Moose: 0
  MooseX::Params::Validate: 0
  MooseX::SemiAffordanceAccessor: 0
  MooseX::StrictConstructor: 0
  namespace::autoclean: 0
resources:
  bugtracker: https://github.com/keedi/Markdown-Pod/issues
  homepage: https://github.com/keedi/Markdown-Pod
  repository: https://github.com/keedi/Markdown-Pod.git
version: 0.005
