---
abstract: 'Convert Markdown to POD'
author:
  - 'Keedi Kim - 김도형 <keedi@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Markdown-Pod
requires:
  Encode: 0
  File::Slurp: 0
  Getopt::Long: 0
  List::Util: 0
  Markdent::Parser: 0
  Markdent::Role::EventsAsMethods: 0
  Markdent::Types: 0
  Moose: 0
  MooseX::Params::Validate: 0
  MooseX::SemiAffordanceAccessor: 0
  MooseX::StrictConstructor: 0
  namespace::autoclean: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Dist/Display.html?Name=Markdown-Pod
  repository: http://github.com/keedi/Markdown-Pod.git
version: 0.003
